from __future__ import annotations

import json
import os
import subprocess
from urllib.error import HTTPError, URLError

from app.schemas import FilingMetadata, RawFiling, WatchlistCompany


DEFAULT_SEC_USER_AGENT = os.environ.get(
    "SEC_USER_AGENT",
    "filing-intelligence/0.1 (local research use; contact: sec-user@example.com)",
)


def _quote_powershell(value: str) -> str:
    return value.replace("'", "''")


def _fetch_url_content(url: str, user_agent: str) -> str:
    escaped_url = _quote_powershell(url)
    escaped_user_agent = _quote_powershell(user_agent)
    command = (
        "$ProgressPreference='SilentlyContinue'; "
        "[Net.ServicePointManager]::SecurityProtocol=[Net.SecurityProtocolType]::Tls12; "
        f"$headers=@{{'User-Agent'='{escaped_user_agent}'}}; "
        f"(Invoke-WebRequest -UseBasicParsing -Headers $headers -Uri '{escaped_url}').Content"
    )
    completed = subprocess.run(
        ["powershell", "-NoProfile", "-Command", command],
        capture_output=True,
        text=True,
        check=False,
    )
    if completed.returncode != 0:
        raise RuntimeError(completed.stderr.strip() or "PowerShell web request failed")

    return completed.stdout


def build_mock_filing_url(company: WatchlistCompany) -> str:
    """Build a deterministic mock filing URL without using the network."""
    ticker = company.ticker.lower()
    return f"https://mock.sec.local/{ticker}/latest-10k"


def _fetch_json(url: str, user_agent: str) -> dict:
    return json.loads(_fetch_url_content(url, user_agent))


def _fetch_text(url: str, user_agent: str) -> str:
    return _fetch_url_content(url, user_agent)


def build_sec_submissions_url(company: WatchlistCompany) -> str:
    """Return the SEC submissions API URL for a company."""
    if not company.cik:
        raise ValueError(f"Missing CIK for {company.ticker}")

    return f"https://data.sec.gov/submissions/CIK{company.cik.zfill(10)}.json"


def find_latest_sec_filing_url(
    company: WatchlistCompany,
    filing_type: str = "10-K",
    user_agent: str = DEFAULT_SEC_USER_AGENT,
) -> FilingMetadata:
    """Find the latest filing archive URL for a company and filing type."""
    submissions_url = build_sec_submissions_url(company)
    submissions = _fetch_json(submissions_url, user_agent=user_agent)
    recent_filings = submissions.get("filings", {}).get("recent", {})

    forms = recent_filings.get("form", [])
    accession_numbers = recent_filings.get("accessionNumber", [])
    filing_dates = recent_filings.get("filingDate", [])
    primary_documents = recent_filings.get("primaryDocument", [])

    for form, accession_number, filing_date, primary_document in zip(
        forms,
        accession_numbers,
        filing_dates,
        primary_documents,
    ):
        if form != filing_type:
            continue

        accession_without_dashes = accession_number.replace("-", "")
        archive_url = (
            f"https://www.sec.gov/Archives/edgar/data/{int(company.cik)}/"
            f"{accession_without_dashes}/{primary_document}"
        )
        return FilingMetadata(
            company=company.company_name,
            ticker=company.ticker,
            filing_type=filing_type,
            filing_date=filing_date,
            source_url=archive_url,
        )

    raise ValueError(f"No recent {filing_type} filing found for {company.ticker}")


def fetch_sec_filing(
    company: WatchlistCompany,
    filing_type: str = "10-K",
    user_agent: str = DEFAULT_SEC_USER_AGENT,
) -> RawFiling:
    """Download a real SEC filing using the submissions API and filing archive URL."""
    metadata = find_latest_sec_filing_url(
        company=company,
        filing_type=filing_type,
        user_agent=user_agent,
    )
    try:
        filing_content = _fetch_text(metadata.source_url, user_agent=user_agent)
    except (HTTPError, URLError, RuntimeError) as exc:
        raise RuntimeError(
            f"Unable to download {company.ticker} {filing_type} filing from SEC"
        ) from exc

    return RawFiling(metadata=metadata, content=filing_content, storage_path="")


def fetch_latest_filing(company: WatchlistCompany) -> RawFiling:
    """Return mock filing metadata and content for the ingestion stage."""
    mock_url = build_mock_filing_url(company)
    metadata = FilingMetadata(
        company=company.name,
        ticker=company.ticker,
        filing_type="10-K",
        filing_date="2026-01-01",
        source_url=mock_url,
    )
    content = (
        f"Mock filing for {company.name} ({company.ticker}).\n"
        f"Source URL: {mock_url}\n"
        "This file was generated by the ingestion skeleton without network access.\n\n"
        "Business\n"
        f"{company.name} business overview placeholder.\n\n"
        "MD&A\n"
        f"{company.name} management discussion placeholder.\n\n"
        "Risk Factors\n"
        f"{company.name} risk factors placeholder.\n\n"
        "Financial Statements\n"
        "Total Revenue: $123,456\n"
        "Operating Income: $45,678\n"
        "Net Income: $34,567\n"
        "Capital Expenditures: 12.3 billion\n"
    )
    return RawFiling(metadata=metadata, content=content, storage_path="")
